cost_index:
    path:     /
    defaults: { _controller: "frediAppBundle:Cost:index" }
    methods:  GET

cost_show:
    path:     /{id}/show
    defaults: { _controller: "frediAppBundle:Cost:show" }
    methods:  GET

cost_new:
    path:     /new
    defaults: { _controller: "frediAppBundle:Cost:new" }
    methods:  [GET, POST]

cost_edit:
    path:     /{id}/edit
    defaults: { _controller: "frediAppBundle:Cost:edit" }
    methods:  [GET, POST]

cost_delete:
    path:     /{id}/delete
    defaults: { _controller: "frediAppBundle:Cost:delete" }
    methods:  DELETE
