fredi_app_cost:
    resource: "@frediAppBundle/Resources/config/routing/cost.yml"
    prefix:   /{associationUniqueId}/cost

fredi_app_costline:
    resource: "@frediAppBundle/Resources/config/routing/costline.yml"
    prefix:   /{associationUniqueId}/costline

fredi_app_association:
        resource: "@frediAppBundle/Resources/config/routing/association.yml"
        prefix:   /association

fredi_app_homepage:
    path:     /
    defaults: { _controller: frediAppBundle:App:landing }

fredi_app_reservation:
        resource: "@frediAppBundle/Resources/config/routing/reservation.yml"
        prefix:   /reservation

fredi_app_reservationline:
        resource: "@frediAppBundle/Resources/config/routing/reservationline.yml"
        prefix:   /reservationline
