services:
  iknsa.core.last_route_event_listener:
        class: fredi\AppBundle\EventListener\LastRouteListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 30 }
